export type ProductCollection = "warriors" | "wizards" | "cyphers";
export type ProductType = "tshirt" | "hoodie";
export type ProductGenre = "men" | "women" | "unisex";

export interface ProductColor {
  name: string;
  hex: string;
}

export interface Product {
  slug: string;
  name: string;
  collection: ProductCollection;
  type: ProductType;
  genre: ProductGenre;
  price: number;
  src: string;        // 300×300 product image
  designSrc: string;  // 1024×1024 design image
  description: string;
  colors: ProductColor[];
}

const DEFAULT_COLORS: ProductColor[] = [
  { name: "Black",  hex: "#111518" },
  { name: "White",  hex: "#f5f5f5" },
  { name: "Orange", hex: "#ed760a" },
];

export const PRODUCTS: Product[] = [
  // ── Warriors ──────────────────────────────────────────────────
  {
    slug: "meme-chad-warrior-tshirt",
    name: "Meme Chad — Warrior",
    collection: "warriors",
    type: "tshirt",
    genre: "unisex",
    price: 50,
    src: "1bis-4-300x300.png",
    designSrc: "1bis-4-1024x1024.png",
    description: "The face of conviction. Bold, uncompromising, orange. This is what a Bitcoiner looks like when they've stopped explaining and started living.",
    colors: DEFAULT_COLORS,
  },
  {
    slug: "perception-vs-reality-tshirt",
    name: "Perception vs. Reality",
    collection: "warriors",
    type: "tshirt",
    genre: "unisex",
    price: 50,
    src: "0004.0-Percept-vs.-Real-1-300x300.png",
    designSrc: "0004.0-Percept-vs.-Real-1-1024x1024.png",
    description: "Two worlds. One truth. Fiat is perception. Bitcoin is reality. Wear the distinction.",
    colors: DEFAULT_COLORS,
  },
  {
    slug: "barbie-for-girls-bitcoin-for-women-tshirt",
    name: "Barbie for Girls",
    collection: "warriors",
    type: "tshirt",
    genre: "women",
    price: 50,
    src: "0003.0-Barbie-for-Girls-Bitcoin-for-Women-300x300.png",
    designSrc: "0003.0-Barbie-for-Girls-Bitcoin-for-Women-1024x1024.png",
    description: "For the women who stacked while everyone else was buying pink plastic. Bitcoin is for everyone. This one's for you.",
    colors: DEFAULT_COLORS,
  },
  {
    slug: "the-statement-tshirt",
    name: "The Statement",
    collection: "warriors",
    type: "tshirt",
    genre: "unisex",
    price: 50,
    src: "1-6-300x300.png",
    designSrc: "1-6-1024x1024.png",
    description: "No need to explain. No need to justify. Some things speak for themselves. Wear the statement.",
    colors: DEFAULT_COLORS,
  },
  {
    slug: "warrior-i-tshirt",
    name: "Warrior I",
    collection: "warriors",
    type: "tshirt",
    genre: "unisex",
    price: 50,
    src: "1-1-300x300.png",
    designSrc: "1-1-1024x1024.png",
    description: "The first warrior. The one who asked questions when everyone else was certain. Keep asking.",
    colors: DEFAULT_COLORS,
  },
  {
    slug: "warrior-ii-tshirt",
    name: "Warrior II",
    collection: "warriors",
    type: "tshirt",
    genre: "men",
    price: 50,
    src: "1-2-300x300.png",
    designSrc: "1-2-1024x1024.png",
    description: "Second in the series. First in conviction. The journey continues.",
    colors: DEFAULT_COLORS,
  },
  {
    slug: "warrior-hoodie",
    name: "Warrior — Hoodie",
    collection: "warriors",
    type: "hoodie",
    genre: "unisex",
    price: 75,
    src: "13-7-300x300.png",
    designSrc: "13-7-1024x1024.png",
    description: "The warrior's armor. Premium organic cotton hoodie. Stay sovereign, stay warm.",
    colors: DEFAULT_COLORS,
  },
  {
    slug: "warrior-declaration-hoodie",
    name: "Declaration — Hoodie",
    collection: "warriors",
    type: "hoodie",
    genre: "unisex",
    price: 75,
    src: "14-8-300x300.png",
    designSrc: "14-8-1024x1024.png",
    description: "A declaration on your back. Every time you walk out the door, you declare independence.",
    colors: DEFAULT_COLORS,
  },

  // ── Wizards ───────────────────────────────────────────────────
  {
    slug: "meme-chad-big-tshirt",
    name: "Meme Chad — Big",
    collection: "wizards",
    type: "tshirt",
    genre: "unisex",
    price: 50,
    src: "1bis-3-300x300.png",
    designSrc: "1bis-3-1024x1024.png",
    description: "The wizard knows what others are still discovering. Patient, humble, inevitable.",
    colors: DEFAULT_COLORS,
  },
  {
    slug: "meme-chad-wizard-tshirt",
    name: "Meme Chad — Wizard",
    collection: "wizards",
    type: "tshirt",
    genre: "unisex",
    price: 50,
    src: "1bis-2-300x300.png",
    designSrc: "1bis-2-1024x1024.png",
    description: "Not everyone sees the magic. The wizard sees the protocol. The others see the price.",
    colors: DEFAULT_COLORS,
  },
  {
    slug: "the-whisper-tshirt",
    name: "The Whisper",
    collection: "wizards",
    type: "tshirt",
    genre: "unisex",
    price: 50,
    src: "1-3-300x300.png",
    designSrc: "1-3-1024x1024.png",
    description: "Signal to those who listen. Invisible to those who don't. The quiet way of the Wizard.",
    colors: DEFAULT_COLORS,
  },
  {
    slug: "encoded-tshirt",
    name: "Encoded",
    collection: "wizards",
    type: "tshirt",
    genre: "unisex",
    price: 50,
    src: "1-4-300x300.png",
    designSrc: "1-4-1024x1024.png",
    description: "Everything that matters has been said. In code. Only wizards read it.",
    colors: DEFAULT_COLORS,
  },
  {
    slug: "hidden-signal-tshirt",
    name: "Hidden Signal",
    collection: "wizards",
    type: "tshirt",
    genre: "women",
    price: 50,
    src: "1-5-300x300.png",
    designSrc: "1-5-1024x1024.png",
    description: "The signal was always there. Hidden in plain sight. For those who learned to look.",
    colors: DEFAULT_COLORS,
  },
  {
    slug: "wizard-hoodie",
    name: "Wizard — Hoodie",
    collection: "wizards",
    type: "hoodie",
    genre: "unisex",
    price: 75,
    src: "5-1-300x300.png",
    designSrc: "5-1-1024x1024.png",
    description: "The wizard's robe, updated for the 21st century. Organic cotton, purple energy, full sovereignty.",
    colors: DEFAULT_COLORS,
  },
  {
    slug: "wizard-deep-hoodie",
    name: "Deep Wizard — Hoodie",
    collection: "wizards",
    type: "hoodie",
    genre: "men",
    price: 75,
    src: "6-1-300x300.png",
    designSrc: "6-1-1024x1024.png",
    description: "Go deeper. The rabbit hole has levels. This hoodie marks the ones who kept going.",
    colors: DEFAULT_COLORS,
  },

  // ── Cyphers ───────────────────────────────────────────────────
  {
    slug: "satoshi-no-time-tshirt",
    name: "Satoshi — No Time",
    collection: "cyphers",
    type: "tshirt",
    genre: "unisex",
    price: 50,
    src: "0006.0-Satoshi-I-dont-have-time-300x300.png",
    designSrc: "0006.0-Satoshi-I-dont-have-time-1024x1024.png",
    description: "\"I don't have time to convince you.\" — Satoshi (probably). Neither do we. The code speaks.",
    colors: DEFAULT_COLORS,
  },
  {
    slug: "cypher-i-tshirt",
    name: "The Cypher I",
    collection: "cyphers",
    type: "tshirt",
    genre: "unisex",
    price: 50,
    src: "2-1-300x300.png",
    designSrc: "2-1-1024x1024.png",
    description: "Encrypted. Sovereign. Private. The first cypher in the series.",
    colors: DEFAULT_COLORS,
  },
  {
    slug: "cypher-ii-tshirt",
    name: "The Cypher II",
    collection: "cyphers",
    type: "tshirt",
    genre: "unisex",
    price: 50,
    src: "3-1-300x300.png",
    designSrc: "3-1-1024x1024.png",
    description: "Keys, nodes, hashes. The building blocks of monetary freedom. Encoded on cotton.",
    colors: DEFAULT_COLORS,
  },
  {
    slug: "cypher-iii-tshirt",
    name: "The Cypher III",
    collection: "cyphers",
    type: "tshirt",
    genre: "unisex",
    price: 50,
    src: "4-1-300x300.png",
    designSrc: "4-1-1024x1024.png",
    description: "Third in the series. The trilogy is complete. The protocol is immutable.",
    colors: DEFAULT_COLORS,
  },
  {
    slug: "meme-chad-cypher-tshirt",
    name: "Meme Chad — Cypher",
    collection: "cyphers",
    type: "tshirt",
    genre: "unisex",
    price: 50,
    src: "9-7-300x300.png",
    designSrc: "9-7-1024x1024.png",
    description: "The cypher wears the meme. The meme carries the truth. You are the node.",
    colors: DEFAULT_COLORS,
  },
  {
    slug: "cypher-hoodie",
    name: "Cypher — Hoodie",
    collection: "cyphers",
    type: "hoodie",
    genre: "unisex",
    price: 75,
    src: "10-1-300x300.png",
    designSrc: "10-1-1024x1024.png",
    description: "Disappear into the code. Reappear in sats. The cypher hoodie for the anonymous sovereign.",
    colors: DEFAULT_COLORS,
  },
  {
    slug: "hash-hoodie",
    name: "Hash — Hoodie",
    collection: "cyphers",
    type: "hoodie",
    genre: "men",
    price: 75,
    src: "11-1-300x300.png",
    designSrc: "11-1-1024x1024.png",
    description: "Every block is a hash. Every hash is a proof. Wear the work.",
    colors: DEFAULT_COLORS,
  },
];

export const COLLECTION_LABELS: Record<ProductCollection, string> = {
  warriors: "Warriors",
  wizards: "Wizards",
  cyphers: "Cyphers",
};

export const COLLECTION_COLORS: Record<ProductCollection, string> = {
  warriors: "bg-[#ed760a] text-black",
  wizards: "bg-[#482B5F] text-white",
  cyphers: "bg-[#222] text-white",
};
